DEMO_JPP/UI-MVC/Controllers/AntwoordController.cs
using JPP.BL;
using JPP.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace JPP.UI.Web.MVC.Controllers
{
    public class AntwoordController : Controller
    {
        AntwoordManager antwManager = new AntwoordManager();
        ModuleManager dossManager = new ModuleManager();
        // GET: Antwoord
        public ActionResult Index()
        {
            return View();
        
        }

        //Antwoord/Lijst

        public ActionResult _partialAntwoordLijst(int? page)
        {

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            
            Dossiermodule dossiermodule = dossManager.GetAllDossierModules().Where(dos => dos.status == ModuleStatus.Open).First();
            IEnumerable<DossierAntwoord> dossierAntwoorden = antwManager.GetDossierAntwoorden(dossiermodule.id);

            ViewBag.Aantal = dossierAntwoorden.Count();
            return PartialView(dossierAntwoorden.ToPagedList(pageNumber, pageSize));

        }
        //Antwoord/Lijst
        public ActionResult Lijst(int id)
        {
            IEnumerable<DossierAntwoord> dossierAntwoorden = antwManager.GetDossierAntwoorden(id);
            return View(dossierAntwoorden);

        }
        // GET: Antwoord/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Antwoord/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Antwoord/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Antwoord/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Antwoord/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Antwoord/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Antwoord/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DEMO_JPP/UI-MVC/Controllers/GebruikerController.cs
using JPP.UI.Web.MVC.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using JPP.UI.Web.MVC;


namespace JPP.UI.Web.MVC.Controllers
{
 
    public class GebruikerController : Controller
    {

        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        public ApplicationRoleManager roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return this.roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set { this.roleManager = value; }
        }



        private ApplicationDbContext apc = new ApplicationDbContext();

        // GET: Gebruiker
        public ActionResult Profiel(string UserName)
        {

            User user = apc.Users.FirstOrDefault(u => u.UserName == UserName);

            var model = new UserRoleViewModel();


            var roles = user.Roles;
            var rolesCollection = new Collection<IdentityRole>();

            foreach (var role in roles)
            {
                var role1 = RoleManager.FindById(role.RoleId);
                rolesCollection.Add(role1);
            }

            model = new UserRoleViewModel { user = user, roles = rolesCollection };


            return View(model);
        }
        // /Gebruiker/WijzigGebruiker
        public ActionResult WijzigGebruiker(string id)
        {

            User user = apc.Users.FirstOrDefault(u => u.Id == id);
            return View(user);


        }

        // /Gebruiker/WijzigGebruiker
        [HttpPost]
        public async Task<ActionResult> WijzigGebruiker(string id, User user)
        {

            var store = new UserStore<User>(apc);
            var userManager = new UserManager<User>(store);

            try
            {
                // TODO: Add update logic here

                apc.Entry(user).State = System.Data.Entity.EntityState.Modified;

                await userManager.UpdateAsync(user);
                apc.SaveChanges();
                userManager.Update(user);
                apc.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {


                return RedirectToAction("Error","Admin");
            }

        }

        // /Gebruiker/VerwijderGebruiker
           [Authorize(Roles = "Admin")]
        public ActionResult VerwijderGebruiker(string id)
        {

            User user = apc.Users.Find(id);

            var model = new UserRoleViewModel();


            var roles = user.Roles;
            var rolesCollection = new Collection<IdentityRole>();

            foreach (var role in roles)
            {
                var role1 = RoleManager.FindById(role.RoleId);
                rolesCollection.Add(role1);
            }

            model = new UserRoleViewModel { user = user, roles = rolesCollection };


            return View(model);
        }


        // /Gebruiker/VerwijderGebruiker
           [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult VerwijderGebruiker(string id, FormCollection collection)
        {
            User user = apc.Users.FirstOrDefault(u => u.Id == id);

            try
            {
                // TODO: Add delete logic here
                if (user != null)
                {

                    apc.Users.Remove(user);
                    apc.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }

        // /Gebruiker/BlokkeerGebruiker
           [Authorize(Roles = "Admin")]
        public ActionResult BlokkeerGebruiker(string id)
        {

            User user = apc.Users.Find(id);

            var model = new UserRoleViewModel();


            var roles = user.Roles;
            var rolesCollection = new Collection<IdentityRole>();

            foreach (var role in roles)
            {
                var role1 = RoleManager.FindById(role.RoleId);
                rolesCollection.Add(role1);
            }

            model = new UserRoleViewModel { user = user, roles = rolesCollection };


            return View(model);

        }
        [Authorize (Roles="Admin")]
        [HttpPost]
        // /Gebruiker/BlokkeerGebruiker
        public async Task<ActionResult> BlokkeerGebruiker(string id, FormCollection collection)
        {

          


            User user = apc.Users.FirstOrDefault(u => u.Id == id);
            var store = new UserStore<User>(apc);
            var userManager = new UserManager<User>(store);

            try
            {
                // TODO: Add update logic here
                if (user.LockoutEndDateUtc == null)
                {
                    user.LockoutEndDateUtc = DateTime.Now.AddDays(30);

                }
                else
                {
                    user.LockoutEndDateUtc = null;
                }


                await userManager.UpdateAsync(user);
                apc.SaveChanges();
                userManager.Update(user);
                apc.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Error", "Admin");
            }


        }

        //Gebuiker/Gebruikers
        public ActionResult Index(int? page)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            IEnumerable<User> users = apc.Users.ToList();
            var model = new Collection<UserRoleViewModel>();

            foreach (var user in users)
            {
                var roles = user.Roles;
                var rolesCollection = new Collection<IdentityRole>();

                foreach (var role in roles)
                {
                    var role1 = RoleManager.FindById(role.RoleId);
                    rolesCollection.Add(role1);
                }

                model.Add(new UserRoleViewModel { user = user, roles = rolesCollection });
            }

            return View(model.ToPagedList(pageNumber, pageSize));
        }

          //Gebuiker/recenteGebruikers
           
           public ActionResult recenteGebruikers()
           {
               

               IEnumerable<User> users = apc.Users.ToList().OrderByDescending(u => u.Created);

               var model = new Collection<UserRoleViewModel>();

               for (int i = 0; i < 5;i++)
               {
                   var roles = users.ElementAt(i).Roles;
                   var rolesCollection = new Collection<IdentityRole>();

                   foreach (var role in roles)
                   {
                       var role1 = RoleManager.FindById(role.RoleId);
                       rolesCollection.Add(role1);
                   }

                   model.Add(new UserRoleViewModel { user = users.ElementAt(i), roles = rolesCollection });
               }

               return View(model);
           }


    }
}

DEMO_JPP/UI-MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JPP.UI.Web.MVC.Controllers
{
    public class HomeController : Controller
    {
        [RequireHttps]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Jongeren participatie platform";

            return View();
        }


        public ActionResult Contact()
        {
            ViewBag.Message = "Jongeren participatie platform";

            return View();
        }

        public ActionResult Diensten()
        {
          

            return View();
        }
    }
}

DEMO_JPP/UI-MVC/Controllers/ModuleController.cs
using JPP.BL;
using JPP.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using JPP.UI.Web.MVC.Models;

namespace JPP.UI.Web.MVC.Controllers
{

    public class ModuleController : Controller
    {

        ModuleManager moduleManager = new ModuleManager();


        // GET: Module
       [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            IEnumerable<Dossiermodule> dossierModules = moduleManager.GetAllDossierModules();

            return View(dossierModules);
        }

        public ActionResult Actief()
        {
           Dossiermodule actieveDossiermodule = moduleManager.GetAllDossierModules().Where(dmod => dmod.status == ModuleStatus.Open).First();

           return View(actieveDossiermodule);
        }
       [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            Dossiermodule dossiermodule = moduleManager.GetDossiermodule(id);

            return View(dossiermodule);
        }
       [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Dossiermodule dossiermodule = moduleManager.GetDossiermodule(id);

            return View(dossiermodule);
        }
        // POST: Module/Delete/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                moduleManager.RemoveDossiermodule(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
       
            Dossiermodule dossiermodule = moduleManager.GetDossiermodule(id);

            return View(dossiermodule);
        }
        // POST: Module/Edit/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, Dossiermodule dossiermodule)
        {
            Dossiermodule dm = moduleManager.GetDossiermodule(id);
            try
            {
                string ms = Request.Form["MyType"];
                if (ms.Length>0 && ms != "0")
                {
             
                int  msi = Int32.Parse(ms);
             
                    ModuleStatus mss = (ModuleStatus)msi;
                    dossiermodule.status = mss;
                }
                else
                {
                    dossiermodule.status = dm.status;
                }
              
                // TODO: Add update logic here

                moduleManager.ChangeDossiermodule(dossiermodule);
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Module/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {

            return View();
        }

        // POST: Module/Create
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(DossiermoduleView dosModule)
        {
            try
            {

                // TODO: Add insert logic here
                moduleManager.AddDossierModule(User.Identity.GetUserName(), dosModule.dossiermodule.naam,
                      dosModule.dossiermodule.beginDatum, dosModule.dossiermodule.eindDatum, dosModule.dossiermodule.volledigheidsPercentage, dosModule.dossiermodule.thema.inhoud,
                      dosModule.dossiermodule.centraleVraag.inhoud,
                      dosModule.vasteVraag.inhoud, dosModule.vasteVraag.verplicht,
                      dosModule.dossiermodule.beloning.naam, dosModule.dossiermodule.beloning.beschrijving, dosModule.dossiermodule.centraleVraag.aantalWinAntwoorden
                      );
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

    }
}

DEMO_JPP/UI-MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "Over ons";
}

@if (Request.IsAuthenticated)
{
    <h1 id="paginaTitel">Over ons</h1>


}
<div class="col-md-6 centraal">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>



    Info

    <address>
        <strong>Website:</strong>   <a href="#">Leuven</a><br />
        <strong>Website:</strong>   <a href="#">Karuur</a><br />
        <strong>Website:</strong>   <a href="http://www.treecompany.be/">Tree Company</a><br />
        <strong>Website:</strong>   <a href="#">De Ambrassade</a><br />
        <strong>Email:</strong> <a href="mailto:info@JPP-L.be">info@JPP-L.be</a> <br />
        <strong>Contacteer ons:</strong> <a href="#">Invulformulier</a>
    </address>
 </div>

DEMO_JPP/UI-MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

@if (Request.IsAuthenticated)
{
    <h1 id="paginaTitel">Contact</h1>


}

<div class="col-md-6 centraal">
    <h2>Over ons</h2>
    <h3>Info</h3>


    <address>
        <strong>Website:</strong>   <a href="#">Leuven</a><br />
        <strong>Website:</strong>   <a href="#">Karuur</a><br />
        <strong>Website:</strong>   <a href="http://www.treecompany.be/">Tree Company</a><br />
        <strong>Website:</strong>   <a href="#">De Ambrassade</a><br />
        <strong>Email:</strong> <a href="mailto:info@JPP-L.be">info@JPP-L.be</a> <br />
        <strong>Contacteer ons:</strong> <a href="#">Invulformulier</a>
    </address>
</div>

<div class="col-md-6 centraal">
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        Blablastraat<br />
        2100 Leuven<br />
        <abbr title="Phone">GSM:</abbr>
        0488/888.888  <br />
        <abbr title="Phone">TEL:</abbr>
        03/33.33.33
    </address>

    <address>
        <strong>Website:</strong>   <a href="http://www.treecompany.be/">treecompany</a><br />
        <strong>Website:</strong>   <a href="#">Leuven</a><br />
        <strong>Email:</strong> <a href="mailto:info@JPP-L.be">sponsor3</a> <br />
        <strong>Contacteer ons:</strong> <a href="#">Invulformulier</a>
    </address>
</div>

DEMO_JPP/UI-MVC/Views/Home/Diensten.cshtml
<div class="row">
    <div class="col-md-4 centraal">

        <a href="@Url.Action("Index", "Bericht")"><img src="~/Images/websitePage logos/iconIdea.png"></a>
        <h2>Bedenk</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
        </p>
    </div>
    <div class="col-md-4 centraal">

        <a href="@Url.Action("Index", "Recensie")"><img src="~/Images/websitePage logos/iconSamenwerken.png"></a>
        <h2>Werk samen</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
        </p>
    </div>
    <div class="col-md-4 centraal">

        <a href="@Url.Action("Index", "Admin")"><img src="~/Images/websitePage logos/iconLike.png"></a>
        <h2>Like</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
        </p>
    </div>

</div>

<div class="row">
    <div class="col-md-4 centraal">

        <a href="@Url.Action("Index", "Bericht")"><img src="~/Images/websitePage logos/iconExpert.png"></a>
        <h2>Vraag aan expert</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
        </p>
    </div>
    <div class="col-md-4 centraal">

        <a href="@Url.Action("Index", "Recensie")"><img src="~/Images/websitePage logos/iconQuestion.png"></a>
        <h2>Comment</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
        </p>
    </div>
    <div class="col-md-4 centraal">

        <a href="@Url.Action("Index", "Admin")"><img src="~/Images/websitePage logos/iconVolgOp.png"></a>
        <h2>Volg op</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
        </p>
    </div>

</div>

DEMO_JPP/UI-MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


        @if (Request.IsAuthenticated)
        {
            <h1 id="paginaTitel"><span id="spanZwart">LOKAAL</span> KABAAL</h1>
            
            <div id="homeIconMenu" class="row verborgen">
                <div class="col-md-4 centraal">
                
                    <a href="#"><img src="~/Images/menu logos/berichtenLogo.png"></a>
                    <h2>Geef uw mening</h2>
                    <h4>Uw mening telt!</h4>
                   
                </div>
                <div class="col-md-4 centraal">
                 
                    <a href="#"><img src="~/Images/menu logos/recensiesLogo.png"></a>
                    <h2>Maak een dossier</h2>
                    <h4>Dien een dossier in en wordt winnaar!</h4>
                </div>
               
                    <div class="col-md-4 centraal">
                        
                        <a href="#"><img src="~/Images/menu logos/adminpanelLogo.png"></a>
                        <h2>Volg op</h2>
                        <h4>Bekijk belangrijke statistieken</h4>
                    </div>
              
            </div>
    <hr />


    <p>
        <button id="hide">Verberg</button>
        <button id="show">Toon</button>
    </p>
            Html.RenderAction("Actief", "Module");

            Html.RenderAction("_partialAntwoordLijst", "Antwoord");

            <hr />


            Html.RenderAction("recenteGebruikers", "Gebruiker");
                Html.RenderAction("recenteGebruikers", "Gebruiker");
                Html.RenderAction("recenteGebruikers", "Gebruiker");





                }
                else
                {
                <div class="row">
                    <div class="col-md-4 centraal">

                        <a href="#"><img src="~/Images/websitePage logos/iconIdea.png"></a>
                        <h2>Bedenk</h2>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
                            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
                        </p>
                    </div>
                    <div class="col-md-4 centraal">

                        <a href="#"><img src="~/Images/websitePage logos/iconSamenwerken.png"></a>
                        <h2>Werk samen</h2>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
                            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
                        </p>
                    </div>
                    <div class="col-md-4 centraal">

                        <a href="#"><img src="~/Images/websitePage logos/iconLike.png"></a>
                        <h2>Like</h2>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
                            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
                        </p>
                    </div>

                </div>
                <hr />
                <div class="row">
                    <div class="col-md-4 centraal">

                        <a href="#"><img src="~/Images/websitePage logos/iconExpert.png"></a>
                        <h2>Vraag aan expert</h2>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
                            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
                        </p>
                    </div>
                    <div class="col-md-4 centraal">

                        <a href="#"><img src="~/Images/websitePage logos/iconQuestion.png"></a>
                        <h2>Comment</h2>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
                            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
                        </p>
                    </div>
                    <div class="col-md-4 centraal">

                        <a href="#"><img src="~/Images/websitePage logos/iconVolgOp.png"></a>
                        <h2>Volg op</h2>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet ullamcorper tempor.
                            Nullam at suscipit arcu. Nunc a magna id diam efficitur scelerisque eget ac eros. Ut consectetur erat diam.
                        </p>
                    </div>

                </div>

                }